### PR TITLE
Make the plugin compatible with Airflow >= "v2.6.0"

### LINKED ISSUE #40: NEW_RELIC_INSERT_KEY causing plugin import failure
I am trying to integrate Newrelic Airflow plugin with Airflow 2.6.1 running on Python 3.9 or 3.11. In both python versions whenever I specify NEW_RELIC_INSERT_KEY as ENV variable it throughs the following error

` ERROR - Failed to import plugin newrelic_plugin
Traceback (most recent call last):
  File "/opt/app-root/lib64/python3.9/site-packages/airflow/plugins_manager.py", line 230, in load_entrypoint_plugins
    if not is_valid_plugin(plugin_class):
  File "/opt/app-root/lib64/python3.9/site-packages/airflow/plugins_manager.py", line 201, in is_valid_plugin
    plugin_obj.validate()
  File "/opt/app-root/lib64/python3.9/site-packages/newrelic_airflow_plugin/newrelic_plugin.py", line 131, in validate
    setattr(Stats, attr, getattr(NewRelicStatsLogger, attr))
AttributeError: 'NoneType' object has no attribute 'incr'`

Here is how I run the Airflow container

`podman run -d -it --rm \
-p 8086:8080 \
-v /tmp/airflow_mount:/opt/airflow \
--env 'NEW_RELIC_INSERT_KEY=xxxxxx' \
--env 'NEW_RELIC_SERVICE_NAME=xxxxxx' \
--env 'NEW_RELIC_HOST=metric-api.eu.newrelic.com' \
airflow
`
If I remove "NEW_RELIC_INSERT_KEY" the plugin loads with no error.

Any hints or help is highly appreciated. Thank you.

### PR DESCRIPTION
**Pull request by shuvaevv**
Closes: #40 

1. Fix the `DummyStatsLogger` import. 
This bug appeared because [DummyStatsLogger was renamed to NoStatsLogger](https://github.com/apache/airflow/pull/30001) in Airflow v2.6.0.
The import of the `DummyStatsLogger` is try-excepted, so the `DummyStatsLogger` class is None. It leads to the `AttributeError: 'NoneType' object has no attribute 'incr'`.

2. Fix the `unexpected keyword argument` error after [the "tag" argument was added](https://github.com/apache/airflow/pull/29093) to StatsLogger in Airflow v2.6.0

### CODE REVIEW

**Comment by TimPansino** [comment]
Hello,

This PR looks helpful, but unfortunately the CI pipeline for this project was canned by security during an incident related to Azure. I'll have to rewrite it in GitHub Actions before we can merge anything. I'll get back to this as soon as we have a new CI in place.

**Comment by TimPansino** [comment]
As of right now we don't have plans to finish fixing the CI, so this is unlikely to be merged or released. We're in talks of archiving this project as it's nowhere near as stable as the builtin OpenTelemetry offering.

If you'd like to give that a try, I'd highly recommend it over the current state of this plugin.

I put up a new documentation page about it [here](https://docs.newrelic.com/docs/more-integrations/open-source-telemetry-integrations/airflow/monitoring-airflow-ot/)

**Comment by thesuperzapper** [comment]
@TimPansino I can confirm that this works in Airflow 2.9.3, can we please merge this?

Otherwise, people won't be able to use the `newrelic-airflow-plugin` with Airflow 2.6+

**Comment by thesuperzapper** [comment]
@TimPansino I also want to highlight that Airflow has a critical issue in its OpenTelemetry integrations, which will cause tasks to fail if the OpenTelemetry endpoint is down:

- https://github.com/apache/airflow/issues/34405#issuecomment-2356954268

The NewRelic __needs to fix this issue__ in airflow if you don't intend to support this plugin anymore.
